---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/posts
  label: Inlägg
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
  - podcast
- type: directory
  path: content/books
  label: Böcker
  create: documents
  match: "**/*"
  templates:
  - bocker
- type: heading
  label: Inställningar
- type: document
  path: config.json
  label: Sidinformation
upload_dir: content/images
public_path: "/content/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv/public"
  instant_preview_command: yarn forestry-preview
